# This workflow will run unit tests on Databricks using GitHub Actions.
# To use this workflow, you need to set up the following secrets in your GitHub repository:
# - DATABRICKS_HOST: The URL of your Databricks workspace (e.g., https://<databricks-instance>.cloud.databricks.com)
# - DATABRICKS_TOKEN: A Databricks personal access token with appropriate permissions to run Databricks Connect.

# name of the workflow
name: Databricks CI
# trigger the workflow on push and pull request events
on: [push, pull_request]
# define the jobs to run in this workflow
jobs:
  # define a job named "run-databricks-ci"
  run-databricks-ci:
    runs-on: ubuntu-latest # specify the operating system for the job
    permissions:
      contents: read
      checks: write
      pull-requests: write
    # define the steps to run in this job
    steps:
      # use the actions/checkout action to check out the repository
      - uses: actions/checkout@v2 # pre-buil action from github, downloads the code in the repository to the Linux machine
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - run: pytest functions --junitxml=unit-testresults.xml # --junitxml saves results to an XML file for the publish step
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }} # from github secrets, the URL of the Databricks workspace
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }} # from github secrets, the personal access token for Databricks
          DATABRICKS_SERVERLESS_COMPUTE_ID: auto
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: unit-testresults.xml
