# This workflow will run unit tests on Databricks using GitHub Actions.
# To use this workflow, you need to set up the following secrets in your GitHub repository:
# - DATABRICKS_HOST: The URL of your Databricks workspace (e.g., https://<databricks-instance>.cloud.databricks.com)
# - DATABRICKS_TOKEN: A Databricks personal access token with appropriate permissions to run Databricks Connect. 

# name of the workflow
name: Databricks CI
# trigger the workflow on push and pull request events
on: [push, pull_request]
# define the jobs to run in this workflow
jobs:
  # define a job named "run-databricks-ci"
  run-databricks-ci:
    runs-on: ubuntu-latest # specify the operating system for the job
    # define the steps to run in this job
    steps:
      # use the actions/checkout action to check out the repository
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - run: |
          echo "[first_access_databrick_1]
          host=${{ secrets.DATABRICKS_HOST }}
          token=${{ secrets.DATABRICKS_TOKEN }}
          serverless_compute_id=auto" > ~/.databrickscfg
      - run: DATABRICKS_CONFIG_PROFILE=first_access_databrick_1 pytest functions --junitxml=unit-testresults.xml
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: unit-testresults.xml
